In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import os

In [3]:
 path = r'/Users/ajahanderson/Documents/Instacart Basket Analysis 11-13-2023'

In [4]:
df_ords_prods_merge =  pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data','orders_products_merged_updated.pkl'))

In [5]:
df = df_ords_prods_merge[:1000000]

In [6]:
df.shape

(1000000, 17)

In [7]:
df.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,days_since_prior_order,add_to_cart_order,reordered,_merge,busiest_day,business_volume,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Regularly busy,Regularly busy,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Regularly busy,Regularly busy,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Regularly busy,Slowiest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Least busy,Slowiest days,Average orders
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Regularly busy,Busiest days,Average orders
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Regularly busy,Regularly busy,Most orders
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Regularly busy,Slowiest days,Most orders
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Regularly busy,Busiest days,Average orders
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Regularly busy,Busiest days,Most orders

In [8]:
df.groupby('product_name')

In [9]:
df.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.562844
2                17.518895
3                16.907152
4                17.537934
5                14.894521
6                16.658449
7                17.072954
8                14.942021
9                15.447580
10               18.681852
11               15.352278
12               14.327957
13               16.578690
14               16.666369
15               16.153766
16               17.768070
17               15.602964
18               19.674252
19               16.924344
20               16.292631
21               25.535596

In [10]:
df.groupby('department_id')['order_number'].mean()

department_id
1     15.562844
2     17.518895
3     16.907152
4     17.537934
5     14.894521
6     16.658449
7     17.072954
8     14.942021
9     15.447580
10    18.681852
11    15.352278
12    14.327957
13    16.578690
14    16.666369
15    16.153766
16    17.768070
17    15.602964
18    19.674252
19    16.924344
20    16.292631
21    25.535596
Name: order_number, dtype: float64

In [11]:
df.groupby('department_id').agg({'order_number':['mean', 'min','max']})

              order_number
                      mean min max
department_id
1                15.562844   1  99
2                17.518895   1  96
3                16.907152   1  99
4                17.537934   1  99
5                14.894521   1  99
6                16.658449   1  99
7                17.072954   1  99
8                14.942021   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.352278   1  99
12               14.327957   1  99
13               16.578690   1  99
14               16.666369   1  99
15               16.153766   1  99
16               17.768070   1  99
17               15.602964   1  99
18               19.674252   1  99
19               16.924344   1  99
20               16.292631   1  99
21               25.535596   1  98

In [12]:
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/136815596.py:1: FutureWarning: The provided callable <function amax at 0x118b90900> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [13]:
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,days_since_prior_order,add_to_cart_order,reordered,_merge,busiest_day,business_volume,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Regularly busy,Slowiest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Least busy,Slowiest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Regularly busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Regularly busy,Regularly busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Regularly busy,Slowiest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Regularly busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Regularly busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,1,0,both,Regularly busy,Regularly busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,both,Regularly busy,Slowiest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,both,Least busy,Slowiest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,both,Regularly busy,Regularly busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,both,Regularly busy,Slowiest days,Most orders,13

In [14]:
 
df_ords_prods_merge[df_ords_prods_merge['user_id'] == 1]

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,days_since_prior_order,add_to_cart_order,reordered,_merge,busiest_day,business_volume,busiest_period_of_day,max_order
103282,196,Soda,77,7,9.0,2539329,1,1,2,8,NaN,1,0,both,Regularly busy,Regularly busy,Average orders,10
103283,196,Soda,77,7,9.0,2398795,1,2,3,7,15.0,1,1,both,Regularly busy,Slowiest days,Average orders,10
103284,196,Soda,77,7,9.0,473747,1,3,3,12,21.0,1,1,both,Regularly busy,Slowiest days,Most orders,10
103285,196,Soda,77,7,9.0,2254736,1,4,4,7,29.0,1,1,both,Least busy,Slowiest days,Average orders,10
103286,196,Soda,77,7,9.0,431534,1,5,4,15,28.0,1,1,both,Least busy,Slowiest days,Most orders,10
103287,196,Soda,77,7,9.0,3367565,1,6,2,7,19.0,1,1,both,Regularly busy,Regularly busy,Average orders,10
103288,196,Soda,77,7,9.0,550135,1,7,1,9,20.0,1,1,both,Regularly busy,Busiest days,Most orders,10
103289,196,Soda,77,7,9.0,3108588,1,8,1,14,14.0,2,1,both,Regularly busy,Busiest days,Most orders,10
103290,196,Soda,77,7,9.0,2295261,1,9,1,16,0.0,4,1,both,Regularly busy,Busiest days,Most orders,10
103291,196,Soda,77,7,9.0,2550362,1,10,4,8,30.0,1,1,both,Least busy,Slowiest days,Average orders,10
5999914,10258,Pistachios,117,19,3.0,2398795,1,2,3,7,15.0,2,0,both,Regularly busy,Slowiest days,Average orders,10
5999915,10258,Pistachios,117,19,3.0,473747,1,3,3,12,21.0,3,1,both,Regularly busy,Slowiest days,Most orders,10
5999916,10258,Pistachios,117,19,3.0,2254736,1,4,4,7,29.0,3,1,both,Least busy,Slowiest days,Average orders,10
5999917,10258,Pistachios,117,19,3.0,431534,1,5,4,15,28.0,3,1,both,Least busy,Slowiest days,Most orders,10
5999918,10258,Pistachios,117,19,3.0,3367565,1,6,2,7,19.0,3,1,both,Regularly busy,Regularly busy,Average orders,10
5999919,10258,Pistachios,117,19,3.0,550135,1,7,1,9,20.0,2,1,both,Regularly busy,Busiest days,Most orders,10
5999920,10258,Pistachios,117,19,3.0,3108588,1,8,1,14,14.0,3,1,both,Regularly busy,Busiest days,Most orders,10
5999921,10258,Pistachios,117,19,3.0,2295261,1,9,1,16,0.0,5,1,both,Regularly busy,Busiest days,Most orders,10
5999922,10258,Pistachios,117,19,3.0,2550362,1,10,4,8,30.0,6,1,both,Least busy,Slowiest days,Average orders,10
6030930,10326,Organic Fuji Apples,24,4,2.7,431534,1,5,4,15,28.0,5,0,both,Least busy,Slowiest days,Most orders,10
7185427,12427,Original Beef Jerky,23,19,4.4,2539329,1,1,2,8,NaN,3,0,both,Regularly busy,Regularly busy,Average orders,10
7185428,12427,Original Beef Jerky,23,19,4.4,2398795,1,2,3,7,15.0,3,1,both,Regularly busy,Slowiest days,Average orders,10
7185429,12427,Original Beef Jerky,23,19,4.4,473747,1,3,3,12,21.0,2,1,both,Regularly busy,Slowiest days,Most orders,10
7185430,12427,Original Beef Jerky,23,19,4.4,2254736,1,4,4,7,29.0,2,1,both,Least busy,Slowiest days,Average orders,10
7185431,12427,Original Beef Jerky,23,19,4.4,431534,1,5,4,15,28.0,2,1,both,Least busy,Slowiest days,Most orders,10
7185432,12427,Original Beef Jerky,23,19,4.4,3367565,1,6,2,7,19.0,2,1,both,Regularly busy,Regularly busy,Average orders,10
7185433,12427,Original Beef Jerky,23,19,4.4,550135,1,7,1,9,20.0,3,1,both,Regularly busy,Busiest days,Most orders,10
7185434,12427,Original Beef Jerky,23,19,4.4,3108588,1,8,1,14,14.0,1,1,both,Regularly busy,Busiest days,Most orders,10
7185435,12427,Original Beef Jerky,23,19,4.4,2295261,1,9,1,16,0.0,6,1,both,Regularly busy,Busiest days,Most orders,10
7185436,12427,Original Beef Jerky,23,19,4.4,2550362,1,10,4,8,30.0,9,1,both,Least busy,Slowiest days,Average orders,10
7481369,13032,Cinnamon Toast Crunch,121,14,4.0,2398795,1,2,3,7,15.0,6,0,both,Regularly busy,Slowiest days,Average orders,10
7481370,13032,Cinnamon Toast Crunch,121,14,4.0,550135,1,7,1,9,20.0,5,1,both,Regularly busy,Busiest days,Most orders,10
7481371,13032,Cinnamon Toast Crunch,121,14,4.0,2550362,1,10,4,8,30.0,8,1,both,Least busy,Slowiest days,Average orders,10
7547160,13176,Bag of Organic Bananas,24,4,10.3,2398795,1,2,3,7,15.0,4,0,both,Regularly busy,Slowiest days,Average orders,10
7547161,13176,Bag of Organic Bananas,24,4,10.3,431534,1,5,4,15,28.0,8,1,both,Least busy,Slowiest days,Most orders,10
8463230,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,2539329,1,1,2,8,NaN,2,0,both,Regularly busy,Regularly busy,Average orders,10
10105105,17122,Honeycrisp Apples,24,4,14.0,431534,1,5,4,15,28.0,6,0,both,Least busy,Slowiest days,Most orders,10
16133357,25133,Organic String Cheese,21,16,8.6,473747,1,3,3,12,21.0,4,0,both,Regularly busy,Slowiest days,Most orders,10
16133358,25133,Organic String Cheese,21,16,8.6,2254736,1,4,4,7,29.0,4,1,both,Least busy,Slowiest days,Average orders,10
16133359,25133,Organic String Cheese,21,16,8.6,431534,1,5,4,15,28.0,4,1,both,Least busy,Slowiest days,Most orders,10
16133360,25133,Organic String Cheese,21,16,8.6,3367565,1,6,2,7,19.0,4,1,both,Regularly busy,Regularly busy,Average orders,10
16133361,25133,Organic String Cheese,21,16,8.6,550135,1,7,1,9,20.0,4,1,both,Regularly busy,Busiest days,Most orders,10
16133362,25133,Organic String Cheese,21,16,8.6,3108588,1,8,1,14,14.0,4,1,both,Regularly busy,Busiest days,Most orders,10
16133363,25133,Organic String Cheese,21,16,8.6,2295261,1,9,1,16,0.0,3,1,both,Regularly busy,Busiest days,Most orders,10
16133364,25133,Organic String Cheese,21,16,8.6,2550362,1,10,4,8,30.0,5,1,both,Least busy,Slowiest days,Average orders,10
16670316,26088,Aged White Cheddar Popcorn,23,19,4.7,2539329,1,1,2,8,NaN,4,0,both,Regularly busy,Regularly busy,Average orders,10
16670317,26088,Aged White Cheddar Popcorn,23,19,4.7,2398795,1,2,3,7,15.0,5,1,both,Regularly busy,Slowiest days,Average orders,10
17037619,26405,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,2539329,1,1,2,8,NaN,5,0,both,Regularly busy,Regularly busy,Average orders,10
17037620,26405,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,2254736,1,4,4,7,29.0,5,1,both,Least busy,Slowiest days,Average orders,10
19859143,30450,Creamy Almond Butter,88,13,3.2,473747,1,3,3,12,21.0,5,0,both,Regularly busy,Slowiest days,Most orders,10
23257420,35951,Organic Unsweetened Almond Milk,91,16,1.3,2550362,1,10,4,8,30.0,7,0,both,Least busy,Slowiest days,Average orders,10
24951219,38928,0% Greek Strained Yogurt,120,16,12.6,2550362,1,10,4,8,30.0,4,0,both,Least busy,Slowiest days,Average orders,10
25482490,39657,Milk Chocolate Almonds,45,19,6.8,2550362,1,10,4,8,30.0,3,0,both,Least busy,Slowiest days,Average orders,10
26775458,41787,Bartlett Pears,24,4,5.0,431534,1,5,4,15,28.0,7,0,both,Least busy,Slowiest days,Most orders,10
29742000,46149,Zero Calorie Cola,77,7,13.4,3108588,1,8,1,14,14.0,5,0,both,Regularly busy,Busiest days,Most orders,10
29742001,46149,Zero Calorie Cola,77,7,13.4,2295261,1,9,1,16,0.0,2,1,both,Regularly busy,Busiest days,Most orders,10
29742002,46149,Zero Calorie Cola,77,7,13.4,2550362,1,10,4,8,30.0,2,1,both,Least busy,Slowiest days,Average orders,10
32063359,49235,Organic Half & Half,53,16,1.8,3108588,1,8,1,14,14.0,6,0,both,Regularly busy,Busiest days,Most orders,10
32063360,49235,Organic Half & Half,53,16,1.8,2295261,1,9,1,16,0.0,1,1,both,Regularly busy,Busiest days,Most orders,10

In [15]:
df_ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,days_since_prior_order,add_to_cart_order,reordered,_merge,busiest_day,business_volume,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Regularly busy,Slowiest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Least busy,Slowiest days,Average orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Regularly busy,Slowiest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Regularly busy,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Regularly busy,Regularly busy,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Regularly busy,Slowiest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Regularly busy,Regularly busy,Most orders,21

In [16]:
pd.options.display.max_rows = None

In [17]:
df_ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,days_since_prior_order,add_to_cart_order,reordered,_merge,busiest_day,business_volume,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Regularly busy,Slowiest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Least busy,Slowiest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Regularly busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Regularly busy,Regularly busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Regularly busy,Slowiest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Regularly busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Regularly busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,1,0,both,Regularly busy,Regularly busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,both,Regularly busy,Slowiest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,both,Least busy,Slowiest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,both,Regularly busy,Regularly busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,both,Regularly busy,Slowiest days,Most orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,18,1,both,Regularly busy,Regularly busy,Average orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,12,1,both,Regularly busy,Regularly busy,Average orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,10,0,both,Regularly busy,Regularly busy,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,9,1,both,Regularly busy,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,9,1,both,Regularly busy,Busiest days,Fewest orders,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,8.0,7,1,both,Regularly busy,Regularly busy,Fewest orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,6.0,6,1,both,Regularly busy,Busiest days,Fewest orders,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,28.0,6,1,both,Regularly busy,Busiest days,Fewest orders,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,7.0,10,1,both,Regularly busy,Busiest days,Most orders,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,7.0,3,1,both,Regularly busy,Busiest days,Most orders,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,0.0,5,1,both,Busiest day,Busiest days,Average orders,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,7.0,11,1,both,Busiest day,Busiest days,Average orders,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,7.0,11,1,both,Busiest day,Busiest days,Average orders,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,7.0,5,1,both,Busiest day,Busiest days,Average orders,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,7.0,15,1,both,Busiest day,Busiest days,Average orders,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,3.0,4,1,both,Least busy,Slowiest days,Average orders,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,16.0,6,1,both,Regularly busy,Regularly busy,Average orders,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,5.0,1,1,both,Regularly busy,Busiest days,Fewest orders,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,6.0,1,1,both,Busiest day,Busiest days,Average orders,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,NaN,2,0,both,Regularly busy,Regularly busy,Most orders,4
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,21.0,2,1,both,Regularly busy,Regularly busy,Most orders,4
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,2.0,3,1,both,Least busy,Slowiest days,Average orders,4
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,NaN,1,0,both,Regularly busy,Busiest days,Most orders,10
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,18.0,6,1,both,Busiest day,Busiest days,Most orders,10
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,8.0,3,1,both,Regularly busy,Busiest days,Most orders,10
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,30.0,10,1,both,Busiest day,Busiest days,Average orders,10
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,25.0,1,1,both,Least busy,Slowiest days,Most orders,10
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,NaN,12,0,both,Busiest day,Busiest days,Most orders,10
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,9.0,10,0,both,Regularly busy,Busiest days,Most orders,23
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,10.0,5,0,both,Regularly busy,Busiest days,Average orders,25
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,7.0,11,0,both,Regularly busy,Slowiest days,Most orders,13
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,NaN,8,0,both,Regularly busy,Regularly busy,Average orders,5
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,30.0,7,0,both,Regularly busy,Regularly busy,Most orders,6
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,NaN,2,0,both,Regularly busy,Busiest days,Most orders,3
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,7.0,8,0,both,Regularly busy,Busiest days,Most orders,42
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,7.0,2,1,both,Regularly busy,Busiest days,Most orders,42
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,7.0,6,1,both,Regularly busy,Slowiest days,Most orders,42
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,5.0,3,1,both,Regularly busy,Regularly busy,Most orders,42
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,4.0,2,1,both,Regularly busy,Busiest days,Most orders,42
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,8.0,1,0,both,Regularly busy,Regularly busy,Average orders,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,30.0,2,0,both,Busiest day,Busiest days,Average orders,9
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,NaN,9,0,both,Regularly busy,Busiest days,Most orders,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,29.0,1,0,both,Regularly busy,Regularly busy,Most orders,4
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,12.0,7,0,both,Busiest day,Busiest days,Most orders,14
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,NaN,11,0,both,Least busy,Slowiest days,Most orders,6
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,4.0,6,0,both,Regularly busy,Regularly busy,Fewest orders,8
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,5.0,5,0,both,Regularly busy,Slowiest days,Most orders,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,5.0,6,1,both,Regularly busy,Busiest days,Average orders,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,13.0,3,1,both,Regularly busy,Busiest days,Average orders,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,10.0,2,0,both,Regularly busy,Regularly busy,Most orders,31
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,6.0,1,1,both,Busiest day,Busiest days,Fewest orders,31
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,9.0,1,1,both,Regularly busy,Regularly busy,Fewest orders,31
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,6.0,2,1,both,Regularly busy,Regularly busy,Most orders,31
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,8.0,2,1,both,Regularly busy,Slowiest days,Most orders,31
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,1.0,13,0,both,Least busy,Slowiest days,Most orders,99
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,7.0,2,0,both,Regularly busy,Slowiest days,Most orders,36
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,21.0,2,0,both,Least busy,Slowiest days,Most orders,9
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,30.0,2,0,both,Busiest day,Busiest days,Most orders,5
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,30.0,1,1,both,Regularly busy,Slowiest days,Most orders,5
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,NaN,11,0,both,Busiest day,Busiest days,Average orders,5
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,30.0,3,0,both,Busiest day,Busiest days,Average orders,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,8.0,2,1,both,Least busy,Slowiest days,Average orders,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,7.0,1,1,both,Least busy,Slowiest days,Most orders,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,14.0,2,1,both,Least busy,Slowiest days,Average orders,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,28.0,1,1,both,Least busy,Slowiest days,Average orders,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,16.0,4,1,both,Least busy,Slowiest days,Average orders,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,1.0,1,1,both,Least busy,Slowiest days,Average orders,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,14.0,1,1,both,Least busy,Slowiest days,Most orders,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,7.0,2,1,both,Least busy,Slowiest days,Most orders,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,8.0,1,1,both,Least busy,Slowiest days,Most orders,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,16.0,7,1,both,Least busy,Slowiest days,Most orders,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,8.0,16,0,both,Least busy,Slowiest days,Average orders,23
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,14.0,5,0,both,Least busy,Slowiest days,Average orders,11
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,NaN,2,0,both,Busiest day,Busiest days,Most orders,5
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,8.0,8,0,both,Regularly busy,Busiest days,Most orders,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,14.0,15,0,both,Regularly busy,Regularly busy,Most orders,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,14.0,9,1,both,Regularly busy,Regularly busy,Most orders,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,10.0,1,0,both,Busiest day,Busiest days,Average orders,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,14.0,4,1,both,Busiest day,Busiest days,Average orders,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,4.0,2,1,both,Regularly busy,Regularly busy,Most orders,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Regularly busy,Slowiest days,Most orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Regularly busy,Busiest days,Most orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Regularly busy,Regularly busy,Most orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Regularly busy,Slowiest days,Most orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Regularly busy,Regularly busy,Most orders,21

In [18]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/2443790946.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Loyal customer' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [19]:
df_ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: count, dtype: int64

In [20]:
df_ords_prods_merge[['user_id','loyalty_flag','order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010  Regular customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006    Loyal customer             2
50     4006    Loyal customer             3
51     4006    Loyal customer             5
52     4006    Loyal customer             9
53     4006    Loyal customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845  Regular customer             6
59     6866      New customer             1

# Task

In [21]:
#2 find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe.
df_ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457687
2                17.277920
3                17.179756
4                17.811403
5                15.213779
6                16.439806
7                17.225773
8                15.340520
9                15.895474
10               20.197148
11               16.170828
12               15.887622
13               16.583304
14               16.757377
15               16.165037
16               17.663250
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

#3. Analyze the result

It seems the values are very close numerically, differing slightly after the decimal point. However, numbers such as 10 and 22 show a deviation of a few digits.

In [22]:
#4. Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/2562752741.py:2: FutureWarning: The provided callable <function amax at 0x118b90900> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [23]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [24]:
# 5. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). 
df_ords_prods_merge.groupby('loyalty_flag').agg({'prices':['mean','min','max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.388747  1.0  99999.0
New customer      13.294370  1.0  99999.0
Regular customer  12.496203  1.0  99999.0

In [25]:
#Create a spending flag for each user based on the average price across all their orders using the following criteria:
df_ords_prods_merge['mean_spent'] = df_ords_prods_merge.groupby(['user_id'])['prices'].transform(np.max)

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/1654251385.py:2: FutureWarning: The provided callable <function amax at 0x118b90900> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['mean_spent'] = df_ords_prods_merge.groupby(['user_id'])['prices'].transform(np.max)

In [26]:
df_ords_prods_merge.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,days_since_prior_order,add_to_cart_order,reordered,_merge,busiest_day,business_volume,busiest_period_of_day,max_order,loyalty_flag,mean_spent
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Regularly busy,Regularly busy,Most orders,32,Regular customer,20.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Regularly busy,Regularly busy,Average orders,32,Regular customer,20.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Busiest day,Busiest days,Average orders,5,New customer,18.5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Regularly busy,Slowiest days,Most orders,3,New customer,14.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Least busy,Slowiest days,Average orders,3,New customer,14.0
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Regularly busy,Busiest days,Average orders,26,Regular customer,14.0
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Regularly busy,Regularly busy,Most orders,9,New customer,10.3
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Regularly busy,Slowiest days,Most orders,12,Regular customer,13.6
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Regularly busy,Busiest days,Average orders,20,Regular customer,13.9
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Regularly busy,Busiest days,Most orders,20,Regular customer,13.9

In [27]:
df_ords_prods_merge.loc[df_ords_prods_merge['mean_spent'] >= 10, 'spending_flag'] = 'High Spender'
df_ords_prods_merge.loc[df_ords_prods_merge['mean_spent'] < 10, 'spending_flag'] = 'Low Spender'

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/3033649175.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'High Spender' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_ords_prods_merge.loc[df_ords_prods_merge['mean_spent'] >= 10, 'spending_flag'] = 'High Spender'

In [28]:
df_ords_prods_merge['spending_flag'].value_counts(dropna = False)

spending_flag
High Spender    32402635
Low Spender        31577
Name: count, dtype: int64

In [29]:
#7. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column.
df.groupby('days_since_prior_order').agg({'order_number': ['median']})

                       order_number
                             median
days_since_prior_order
0.0                            19.0
1.0                            24.0
2.0                            23.0
3.0                            22.0
4.0                            19.0
5.0                            17.0
6.0                            15.0
7.0                            14.0
8.0                            13.0
9.0                            12.0
10.0                           12.0
11.0                           11.0
12.0                           10.0
13.0                           10.0
14.0                            9.0
15.0                            9.0
16.0                            9.0
17.0                            9.0
18.0                            9.0
19.0                            8.0
20.0                            8.0
21.0                            8.0
22.0                            8.0
23.0                            7.0
24.0                            7.0
25.0                            7.0
26.0                            7.0
27.0                            7.0
28.0                            7.0
29.0                            7.0
30.0                            5.0

In [30]:
df_ords_prods_merge['order_frequency'] = df_ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.max)

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/1492550121.py:1: FutureWarning: The provided callable <function amax at 0x118b90900> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_ords_prods_merge['order_frequency'] = df_ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.max)

In [31]:
df_ords_prods_merge.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,...,reordered,_merge,busiest_day,business_volume,busiest_period_of_day,max_order,loyalty_flag,mean_spent,spending_flag,order_frequency
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,0,both,Regularly busy,Regularly busy,Most orders,32,Regular customer,20.0,High Spender,30.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,both,Regularly busy,Regularly busy,Average orders,32,Regular customer,20.0,High Spender,30.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,0,both,Busiest day,Busiest days,Average orders,5,New customer,18.5,High Spender,8.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,0,both,Regularly busy,Slowiest days,Most orders,3,New customer,14.0,High Spender,13.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,1,both,Least busy,Slowiest days,Average orders,3,New customer,14.0,High Spender,13.0
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,0,both,Regularly busy,Busiest days,Average orders,26,Regular customer,14.0,High Spender,30.0
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,0,both,Regularly busy,Regularly busy,Most orders,9,New customer,10.3,High Spender,30.0
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,0,both,Regularly busy,Slowiest days,Most orders,12,Regular customer,13.6,High Spender,30.0
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,0,both,Regularly busy,Busiest days,Average orders,20,Regular customer,13.9,High Spender,25.0
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,1,both,Regularly busy,Busiest days,Most orders,20,Regular customer,13.9,High Spender,25.0

In [33]:
df_ords_prods_merge.loc[df_ords_prods_merge['order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'
df_ords_prods_merge.loc[(df_ords_prods_merge['order_frequency'] <= 20) & (df_ords_prods_merge['order_frequency'] > 10), 'order_frequency_flag'] = 'Regular customer'
df_ords_prods_merge.loc[df_ords_prods_merge['order_frequency'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

/var/folders/5t/s295bnhn7bvf1407s3py_b8h0000gn/T/ipykernel_67792/4087780712.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Non-frequent customer' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_ords_prods_merge.loc[df_ords_prods_merge['order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [34]:
df_ords_prods_merge['order_frequency_flag'].value_counts(dropna=False)

order_frequency_flag
Non-frequent customer    24509620
Regular customer          6539471
Frequent customer         1385121
Name: count, dtype: int64

In [35]:
df_ords_prods_merge.head(10)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,day_of_week_order_placed,order_time,...,_merge,busiest_day,business_volume,busiest_period_of_day,max_order,loyalty_flag,mean_spent,spending_flag,order_frequency,order_frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,both,Regularly busy,Regularly busy,Most orders,32,Regular customer,20.0,High Spender,30.0,Non-frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,both,Regularly busy,Regularly busy,Average orders,32,Regular customer,20.0,High Spender,30.0,Non-frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,both,Busiest day,Busiest days,Average orders,5,New customer,18.5,High Spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,both,Regularly busy,Slowiest days,Most orders,3,New customer,14.0,High Spender,13.0,Regular customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,both,Least busy,Slowiest days,Average orders,3,New customer,14.0,High Spender,13.0,Regular customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,both,Regularly busy,Busiest days,Average orders,26,Regular customer,14.0,High Spender,30.0,Non-frequent customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,both,Regularly busy,Regularly busy,Most orders,9,New customer,10.3,High Spender,30.0,Non-frequent customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,both,Regularly busy,Slowiest days,Most orders,12,Regular customer,13.6,High Spender,30.0,Non-frequent customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,both,Regularly busy,Busiest days,Average orders,20,Regular customer,13.9,High Spender,25.0,Non-frequent customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,both,Regularly busy,Busiest days,Most orders,20,Regular customer,13.9,High Spender,25.0,Non-frequent customer

In [36]:
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merged_updated_2_part1.pkl'))